import test from 'node:test';
import assert from 'node:assert/strict';
import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {InMemoryTransport} from '@modelcontextprotocol/sdk/inMemory.js';
import {registerCardView,normalizeCards,RESOURCE_URI} from '../src/card-view.ts';
import {widgetHtml} from '../src/widget-html.ts';
// @ts-ignore jsdom is only the test DOM; production has no UI dependencies.
import {JSDOM} from 'jsdom';
const payload={cards:[{id:'1',title:'<img src=x onerror=alert(1)>',status:'running',assigneeAgentId:'demo',updatedAt:'2026-10-02T00:00:00Z',request:'private detail'},{id:'2',title:'Second',status:'done'}]};
test('normalizes current card contract, strips private details, limits output',()=>{const d=normalizeCards(payload,1);assert.equal(d.total,2);assert.equal(d.truncated,true);assert.equal(d.cards[0].assignee,'demo');assert.equal('request' in d.cards[0],false)});
test('unknown status and invalid date do not pretend known state',()=>{assert.deepEqual(normalizeCards({cards:[{id:'a',title:'A',status:'future',updatedAt:'bad'}]}).cards[0],{id:'a',title:'A',status:'unknown',assignee:'',updatedAt:null})});
test('invalid response is rejected, empty array is valid',()=>{assert.throws(()=>normalizeCards({tasks:[]}));assert.equal(normalizeCards({cards:[]}).total,0)});
async function connect(){const server=new McpServer({name:'test',version:'1'});registerCardView(server);const client=new Client({name:'test',version:'1'});const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);return {server,client};}
test('actual MCP tools/list, resources/read and tools/call work',async()=>{const {server,client}=await connect();try{const {tools}=await client.listTools();assert.equal(tools.length,1);assert.equal(tools[0].annotations?.readOnlyHint,true);assert.equal((tools[0]._meta?.ui as any).resourceUri,RESOURCE_URI);const r=await client.readResource({uri:RESOURCE_URI});assert.equal(r.contents[0].mimeType,'text/html;profile=mcp-app');const result=await client.callTool({name:'render_soulstream_cards',arguments:{cards:normalizeCards(payload,1).cards}});assert.equal((result.structuredContent as any).cards.length,1);const bad=await client.callTool({name:'render_soulstream_cards',arguments:{cards:[{id:'',title:'',status:'invalid'}]}});assert.equal(bad.isError,true)}finally{await client.close();await server.close()}});
test('renderer rejects extra sensitive fields and oversized batches',async()=>{const {server,client}=await connect();try{for(const cards of [[{id:'1',title:'A',status:'todo',request:'private detail'}],Array.from({length:101},(_,i)=>({id:String(i),title:'A',status:'todo'}))]){const r=await client.callTool({name:'render_soulstream_cards',arguments:{cards}});assert.equal(r.isError,true)}}finally{await client.close();await server.close()}});
test('UI renders safely, filters repeatedly, handles empty and error states',()=>{const dom=new JSDOM(widgetHtml,{runScripts:'dangerously'});const w=dom.window;const send=(params:unknown)=>w.dispatchEvent(new w.MessageEvent('message',{source:w,data:{jsonrpc:'2.0',method:'ui/notifications/tool-result',params}}));send({structuredContent:normalizeCards(payload)});assert.equal(w.document.querySelectorAll('article').length,2);assert.equal(w.document.querySelectorAll('img').length,0);const filter=w.document.getElementById('filter');filter.value='done';filter.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('article').length,1);filter.value='all';filter.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('article').length,2);send({structuredContent:normalizeCards({cards:[]})});assert.match(w.document.getElementById('notice').textContent,/표시할 카드/);send({isError:true});assert.match(w.document.getElementById('summary').textContent,/실패/);dom.window.close()});

test('plugin identity, empty mappings and embedded HTML stay consistent',async()=>{const {readFile}=await import('node:fs/promises');assert.equal(widgetHtml,await readFile(new URL('../public/cards.html',import.meta.url),'utf8'));const plugin=JSON.parse(await readFile(new URL('../plugin.json',import.meta.url),'utf8'));assert.equal(plugin.name,'soulstream-card-renderer');const mcp=JSON.parse(await readFile(new URL('../mcp.json',import.meta.url),'utf8'));assert.deepEqual(mcp.mcpServers,{})});
test('HTTP preview, MCP initialization and request size limit',async()=>{const {createRendererHttpServer}=await import('../src/server.ts');const http=createRendererHttpServer();await new Promise<void>(resolve=>http.listen(0,'127.0.0.1',resolve));const address=http.address();assert(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}`;try{assert.equal((await fetch(url+'/preview')).status,200);assert.equal((await fetch(url+'/unknown')).status,404);const headers={'content-type':'application/json',accept:'application/json, text/event-stream'};const r=await fetch(url+'/mcp',{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'test',version:'1'}}})});assert.equal(r.status,200);assert.equal((await r.json() as any).result.serverInfo.name,'soulstream-card-renderer');assert.equal((await fetch(url+'/mcp',{method:'POST',headers,body:'x'.repeat(129*1024)})).status,413);assert.equal((await fetch(url+'/mcp',{method:'POST',headers,body:'not-json'})).status,400)}finally{await new Promise<void>(resolve=>http.close(()=>resolve()))}});
