import test from 'node:test';
import assert from 'node:assert/strict';
import {widgetHtml} from '../src/widget-html.ts';
// @ts-ignore test-only DOM
import {JSDOM} from 'jsdom';
function harness(){
 const sent:any[]=[];const timers=new Map<number,{fn:()=>void;delay:number}>();let next=0;
 const dom=new JSDOM(widgetHtml,{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w:any){w.postMessage=(m:any)=>sent.push(m);w.setTimeout=(fn:()=>void,delay:number)=>{timers.set(++next,{fn,delay});return next};w.clearTimeout=(id:number)=>timers.delete(id)}});
 const w=dom.window;const send=(data:any)=>w.dispatchEvent(new w.MessageEvent('message',{source:w,data}));
 const data=(title:string,folderId='one')=>({structuredContent:{cards:[{id:'a',title,status:'running',assignee:'',updatedAt:null}],total:1,truncated:false,sync:{folderId,limit:100,refreshSeconds:30,fetchedAt:'2026-10-02T00:00:00Z'}}});
 const model=(title:string,folder='one')=>send({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:data(title,folder)});
 const click=()=>w.document.getElementById('refresh').click();const calls=()=>sent.filter(m=>m.method==='tools/call');
 send({jsonrpc:'2.0',id:1,result:{}});
 return {w,dom,sent,timers,send,data,model,click,calls};
}
test('live initial data, manual refresh, and periodic refresh use same MCP data tool',()=>{const h=harness();h.model('Initial');assert.equal(h.w.document.querySelector('article h2').textContent,'Initial');h.click();h.click();assert.equal(h.calls().length,1);const req=h.calls()[0];assert.equal(req.params.name,'list_live_cards');assert.equal(req.params.arguments.folder_id,'one');h.send({jsonrpc:'2.0',id:req.id,result:h.data('Updated')});assert.equal(h.w.document.querySelector('article h2').textContent,'Updated');const timer=[...h.timers.values()].find(t=>t.delay===30000);assert(timer);timer.fn();assert.equal(h.calls().length,2);h.w.dispatchEvent(new h.w.Event('pagehide'));assert.equal(h.timers.size,0);h.dom.window.close()});
test('new model result invalidates overlapping response; teardown clears timers and pending call',()=>{const h=harness();h.model('First');h.click();const old=h.calls()[0];h.model('New scope','two');h.send({jsonrpc:'2.0',id:old.id,result:h.data('Obsolete')});assert.equal(h.w.document.querySelector('article h2').textContent,'New scope');h.click();assert.equal(h.calls()[1].params.arguments.folder_id,'two');h.send({jsonrpc:'2.0',id:'close',method:'ui/resource-teardown'});assert.equal(h.timers.size,0);h.send({jsonrpc:'2.0',id:h.calls()[1].id,result:h.data('Late')});assert.equal(h.w.document.querySelectorAll('article').length,0);assert.equal(h.sent.at(-1).id,'close');h.dom.window.close()});
test('refresh timeout retains stale data with error; permission error clears data without saying empty',()=>{const h=harness();h.model('Old');h.click();const timeout=[...h.timers.values()].find(t=>t.delay===10000);assert(timeout);timeout.fn();assert.match(h.w.document.getElementById('notice').textContent,/이전 데이터/);assert.equal(h.w.document.querySelectorAll('article').length,1);h.click();h.send({jsonrpc:'2.0',id:h.calls().at(-1).id,result:{isError:true,structuredContent:{syncError:{authorization:true}}}});assert.equal(h.w.document.querySelectorAll('article').length,0);assert.match(h.w.document.getElementById('summary').textContent,/실패/);h.w.dispatchEvent(new h.w.Event('pagehide'));h.dom.window.close()});
test('hidden widget pauses polling and resumes with a refresh',()=>{const h=harness();h.model('Old');Object.defineProperty(h.w.document,'hidden',{value:true,configurable:true});h.w.document.dispatchEvent(new h.w.Event('visibilitychange'));assert.equal([...h.timers.values()].filter(t=>t.delay===30000).length,0);Object.defineProperty(h.w.document,'hidden',{value:false,configurable:true});h.w.document.dispatchEvent(new h.w.Event('visibilitychange'));assert.equal(h.calls().length,1);h.w.dispatchEvent(new h.w.Event('pagehide'));h.dom.window.close()});

test('failed new view never resumes polling the previous folder',()=>{const h=harness();h.model('Old folder');h.click();h.send({jsonrpc:'2.0',method:'ui/notifications/tool-result',params:{isError:true}});assert.equal(h.w.document.querySelectorAll('article').length,0);assert.equal(h.w.document.getElementById('refresh').hidden,true);assert.equal(h.timers.size,0);h.w.dispatchEvent(new h.w.Event('pagehide'));h.dom.window.close()});
