export const DASHBOARD_PANEL_INSET_PX = 8;
export const DASHBOARD_ITEM_GAP_PX = 8;

export const DASHBOARD_SESSION_CARD_HEIGHT_PX = 132;
export const DASHBOARD_SESSION_ROW_HEIGHT_PX =
  DASHBOARD_SESSION_CARD_HEIGHT_PX + DASHBOARD_ITEM_GAP_PX;
