import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {compile} from '@tailwindcss/node';
import {Scanner} from '@tailwindcss/oxide';
const plugin=fileURLToPath(new URL('..',import.meta.url));
const compiled=await compile(readFileSync(new URL('../src/widget.css',import.meta.url),'utf8'),{base:fileURLToPath(new URL('../src',import.meta.url)),onDependency(){}});
const scanner=new Scanner({sources:compiled.sources});
const css=compiled.build(scanner.scan());
const bundle=await build({entryPoints:[fileURLToPath(new URL('../src/widget-client.tsx',import.meta.url))],bundle:true,write:false,
 format:'iife',platform:'browser',target:'es2022',jsx:'automatic',minify:true,nodePaths:[plugin+'/node_modules'],
 alias:{react:plugin+'/node_modules/react','react-dom':plugin+'/node_modules/react-dom'},
 define:{'process.env.NODE_ENV':'"production"'},metafile:true});
const inputs=Object.keys(bundle.metafile.inputs);
if(inputs.some(p=>/dashboard-store|card-store|card-api|card-navigation|LiquidGlassProvider/.test(p)))throw Error('Widget pulled in dashboard state or network dependencies');
const js=bundle.outputFiles[0].text.replaceAll('</script','<\\/script');
const html=readFileSync(new URL('../public/cards.template.html',import.meta.url),'utf8').replace('<!--WIDGET_CSS-->',css).replace('<!--WIDGET_JS-->',js);
writeFileSync(new URL('../public/cards.html',import.meta.url),html);
writeFileSync(new URL('../src/widget-html.ts',import.meta.url),'// Generated by build:widget; self-contained HTML/CSS/JS.\nexport const widgetHtml = '+JSON.stringify(html)+';\n');
console.log(`Widget: ${inputs.length} inputs, ${Buffer.byteLength(html)} bytes; no dashboard store/API/router`);
