import React from 'react';
import { act, render } from '@testing-library/react-native';
import { PersistentSessionProvider, usePersistentSessionHost } from '../PersistentSessionContext';
import { TabNavigator } from '../TabNavigator';
import { getBottomTabCaptures, getNativeStackCaptures, resetNavigationCapture } from './navigationCaptureMock';
const mockList = jest.fn();
jest.mock('@expo/vector-icons/Ionicons', () => 'Ionicons');
jest.mock('../../components/planner/FolderWorkspace', () => ({ FolderWorkspace: () => null }));
jest.mock('../../screens/ChatScreen', () => ({ ChatScreen: () => null }));
jest.mock('../../api/client', () => ({ createApiClient: () => ({ listPersistentSessions: mockList }) }));
jest.mock('@react-navigation/native-stack', () => ({ createNativeStackNavigator: require('./navigationCaptureMock').createNativeStackNavigatorCapture }));
jest.mock('@react-navigation/bottom-tabs', () => ({ createBottomTabNavigator: require('./navigationCaptureMock').createBottomTabNavigatorCapture }));
jest.mock('@react-navigation/native', () => ({ useIsFocused: () => true, useFocusEffect: jest.fn() }));
jest.mock('../../hooks/useSessionsStream', () => ({ useSessionsStream: jest.fn() }));
jest.mock('../../hooks/useNodeConnectivityStream', () => ({ useNodeConnectivityStream: jest.fn() }));
jest.mock('../../screens/DailyPlannerScreen', () => ({ DailyPlannerScreen: require('react').forwardRef(() => null) }));
jest.mock('../../screens/SettingsScreen', () => ({ SettingsScreen: () => null }));
jest.mock('../../components/planner/CardDetailSheet', () => ({ CardDetailContent: jest.fn(() => null) }));
jest.mock('../../screens/PersistentSessionScreen', () => ({ PersistentSessionScreen: jest.fn(() => null) }));
import { useSettingsStore } from '../../store/settingsStore';
import { PersistentSessionScreen } from '../../screens/PersistentSessionScreen';
import { CardDetailContent } from '../../components/planner/CardDetailSheet';
import { createSurfaceRoles, useTokens } from '../../theme';
import { renderHook } from '@testing-library/react-native';
let host: ReturnType<typeof usePersistentSessionHost>;
function Probe() { host = usePersistentSessionHost(); return null; }
test('정확한 가운데 슬롯만 기본 이동을 막고 같은 id로 scene을 전환하며 다른 탭 입구는 대화로 연다', async () => {
  resetNavigationCapture();
  useSettingsStore.setState({ serverUrl: 'https://public.invalid' });
  mockList.mockResolvedValue({ sessions: [{ session_id: 'pas', display_name: 'PAS' }], create_defaults: null });
  render(<PersistentSessionProvider><Probe /><TabNavigator /></PersistentSessionProvider>);
  const tabs = getBottomTabCaptures()[0];
  expect(tabs.screens.map(s => s.name)).toEqual(['DailyTab', 'FolderTab', 'PersistentTab', 'FeedTab', 'SettingsTab']);
  const navigation = { isFocused: () => false, navigate: jest.fn() };
  const preventDefault = jest.fn();
  for (const tab of tabs.screens.filter(s => s.name !== 'PersistentTab')) expect(tab.listeners({ navigation }).tabPress).toBeUndefined();
  const press = tabs.screens[2].listeners({ navigation }).tabPress;
  await act(async () => { await press({ preventDefault }); });
  expect(navigation.navigate).toHaveBeenCalledWith('PersistentTab');
  expect(host.store.getState()).toMatchObject({ scene: 'conversation', session: { session_id: 'pas' } });
  const active = tabs.screens[2].listeners({ navigation: { ...navigation, isFocused: () => true } }).tabPress;
  act(() => active({ preventDefault }));
  expect(host.store.getState()).toMatchObject({ scene: 'cards', selectedCardId: null });
  act(() => host.store.getState().selectCard('card'));
  act(() => active({ preventDefault }));
  expect(host.store.getState()).toMatchObject({ scene: 'conversation', selectedCardId: null });
  expect(mockList).toHaveBeenCalledTimes(1);
  expect(preventDefault).toHaveBeenCalledTimes(3);
});
test('Feed 스택에 일반 Chat이 있고 PAS 스택의 기존 카드 상세 goBack은 같은 요약으로 돌아간다', () => {
  resetNavigationCapture();
  render(<PersistentSessionProvider><Probe /><TabNavigator /></PersistentSessionProvider>);
  const tabs = getBottomTabCaptures()[0];
  for (const tab of tabs.screens) render(<PersistentSessionProvider>{React.createElement(tab.component)}</PersistentSessionProvider>);
  const feed = getNativeStackCaptures().find(stack => stack.screens[0]?.name === 'Feed')!;
  expect(feed.screens.map(s => s.name)).toEqual(['Feed', 'Search', 'Chat']);
  expect(feed.screens[2].options.gestureEnabled).toBe(false);
  const pas = getNativeStackCaptures().find(stack => stack.screens[0]?.name === 'PersistentSession')!;
  expect(pas.screens.map(s => s.name)).toEqual(['PersistentSession', 'CardDetail']);
  expect((pas.navigatorProps?.screenOptions as any).contentStyle).toEqual(createSurfaceRoles(renderHook(() => useTokens()).result.current).canvas.tokenStyle);
  const navigation = { addListener: jest.fn(() => () => {}), getParent: jest.fn(), goBack: jest.fn(), navigate: jest.fn() };
  render(<PersistentSessionProvider><Probe />{React.createElement(pas.screens[0].component, { navigation })}</PersistentSessionProvider>);
  act(() => { host.store.getState().open({ session_id: 'pas' } as any); host.store.getState().selectCard('card'); });
  jest.mocked(PersistentSessionScreen).mock.calls.at(-1)![0].onOpenCard('card');
  expect(navigation.navigate).toHaveBeenCalledWith('CardDetail', { cardId: 'card' });
  render(React.createElement(pas.screens[1].component, { route: { params: { cardId: 'card' } }, navigation }));
  jest.mocked(CardDetailContent).mock.calls.at(-1)![0].onClose();
  expect(navigation.goBack).toHaveBeenCalledTimes(1);
  expect(host.store.getState()).toMatchObject({ scene: 'cards', selectedCardId: 'card', session: { session_id: 'pas' } });
});
