/** Live web dialog variants. Desktop selection menus and tooltips are not independent dialogs. */
export const dialoguesInventory = [
  {
    section: "folders",
    id: "project-create",
    name: "새 폴더 · 프로젝트",
    component: "ProjectDialog",
  },
  {
    section: "folders",
    id: "project-edit",
    name: "폴더 편집 · 프로젝트",
    component: "ProjectDialog",
  },
  {
    section: "folders",
    id: "folder-create",
    name: "새 폴더 · 보드",
    component: "FolderDialog",
  },
  {
    section: "folders",
    id: "archive-nav",
    name: "폴더 보관 · 탐색",
    component: "FolderArchiveDialog",
  },
  {
    section: "folders",
    id: "archive-detail",
    name: "폴더 보관 · 상세",
    component: "FolderDetailArchiveDialog",
  },
  {
    section: "folders",
    id: "archive-board",
    name: "폴더 보관 · 보드",
    component: "FolderDialog",
  },
  {
    section: "folders",
    id: "folder-settings",
    name: "폴더 설정",
    component: "FolderSettingsDialog",
  },
  {
    section: "folders",
    id: "parent-move",
    name: "다른 프로젝트로 이동",
    component: "FolderParentMoveDialog",
  },
  {
    section: "sessions",
    id: "session-move",
    name: "세션 폴더 이동",
    component: "FolderMoveDialog",
  },
  {
    section: "sessions",
    id: "session-rename",
    name: "세션 이름 변경",
    component: "RenameSessionDialog",
  },
  {
    section: "sessions",
    id: "session-delete",
    name: "세션 삭제 · 한 개",
    component: "SessionDeleteDialog",
  },
  {
    section: "sessions",
    id: "sessions-delete",
    name: "세션 삭제 · 여러 개",
    component: "SessionDeleteDialog",
  },
  {
    section: "sessions",
    id: "continue-error",
    name: "세션 이어서 시작 실패",
    component: "SessionContinueErrorDialog",
  },
  {
    section: "sessions",
    id: "new-session",
    name: "새 세션",
    component: "SessionSuccessionModal",
  },
  {
    section: "sessions",
    id: "succession",
    name: "세션 승계",
    component: "SessionSuccessionModal",
  },
  {
    section: "sessions",
    id: "search",
    name: "세션·폴더 검색",
    component: "SearchModal",
  },
  {
    section: "cards",
    id: "card-create",
    name: "새 카드",
    component: "CardCreateDialog",
  },
  {
    section: "documents",
    id: "document-move",
    name: "문서 폴더 이동",
    component: "FolderMoveDialog",
  },
  {
    section: "documents",
    id: "document-delete",
    name: "문서 삭제",
    component: "MarkdownDeleteDialog",
  },
  {
    section: "documents",
    id: "rename-markdown",
    name: "보드 문서 이름 변경",
    component: "BoardRenameDialog",
  },
  {
    section: "documents",
    id: "rename-folder",
    name: "보드 폴더 이름 변경",
    component: "BoardRenameDialog",
  },
  {
    section: "documents",
    id: "rename-frame",
    name: "보드 프레임 이름 변경",
    component: "BoardRenameDialog",
  },
  {
    section: "documents",
    id: "board-move-session",
    name: "보드 세션 이동",
    component: "BoardMoveDialog",
  },
  {
    section: "documents",
    id: "board-move-markdown",
    name: "보드 문서 이동",
    component: "BoardMoveDialog",
  },
  {
    section: "documents",
    id: "board-move-asset",
    name: "보드 파일 이동",
    component: "BoardMoveDialog",
  },
  {
    section: "documents",
    id: "board-move-custom",
    name: "보드 커스텀 뷰 이동",
    component: "BoardMoveDialog",
  },
  {
    section: "settings",
    id: "settings",
    name: "서버 설정 · 모든 탭",
    component: "ConfigModal",
  },
  {
    section: "settings",
    id: "user-create",
    name: "사용자 추가",
    component: "ConfigModal / UserManagementTab",
  },
  {
    section: "settings",
    id: "user-edit",
    name: "사용자 편집",
    component: "ConfigModal / UserManagementTab",
  },
  {
    section: "settings",
    id: "confirm-user",
    name: "사용자 삭제 · browser confirm",
    component: "confirmUserRemoval",
  },
  {
    section: "settings",
    id: "confirm-recurring",
    name: "반복 작업 보관 · browser confirm",
    component: "confirmRecurringArchive",
  },
  {
    section: "settings",
    id: "ritual",
    name: "아침 정리",
    component: "RitualModal",
  },
  {
    section: "overlays",
    id: "atom-add",
    name: "atom 컨텍스트 추가",
    component: "ProjectContextEditor",
  },
  {
    section: "overlays",
    id: "atom-edit",
    name: "atom 컨텍스트 편집",
    component: "ProjectContextEditor",
  },
  {
    section: "overlays",
    id: "defaults-add",
    name: "기본 에이전트 추가",
    component: "ProjectContextEditor",
  },
  {
    section: "overlays",
    id: "defaults-edit",
    name: "기본 에이전트 편집",
    component: "ProjectContextEditor",
  },
  {
    section: "overlays",
    id: "card-image",
    name: "카드 보고 이미지 확대",
    component: "CardTimeline",
  },
  {
    section: "overlays",
    id: "file-image",
    name: "첨부 이미지 확대",
    component: "FileAttachmentPreview",
  },
  {
    section: "overlays",
    id: "card-detail",
    name: "카드 상세 확대",
    component: "CardWorkspace",
  },
  {
    section: "overlays",
    id: "card-board",
    name: "카드 보드 확대",
    component: "CardBoardWorkspace",
  },
  {
    section: "overlays",
    id: "document-overlay",
    name: "보드 문서 편집기 확대",
    component: "FolderDocumentOverlay / MarkdownDocumentPanel",
  },
  {
    section: "overlays",
    id: "v3-sheet",
    name: "모바일 작업 액션 시트",
    component: "V3ContextMenu",
  },
  {
    section: "overlays",
    id: "folder-sheet",
    name: "모바일 폴더 액션 시트",
    component: "FolderContextMenu",
  },
  {
    section: "overlays",
    id: "session-sheet",
    name: "모바일 세션 액션 시트",
    component: "SessionContextMenu",
  },
] as const;
export type DialogueId = (typeof dialoguesInventory)[number]["id"];
export const dialoguesSections = [
  { id: "folders", title: "폴더" },
  { id: "sessions", title: "세션" },
  { id: "cards", title: "카드와 첨부" },
  { id: "documents", title: "문서와 보드" },
  { id: "settings", title: "설정" },
  { id: "overlays", title: "팝오버와 확대" },
] as const;
