export const WORKTREE_OPERATION_TIMEOUT_MS = 120_000;
export const WORKTREE_CREATE_TIMEOUT_DEFAULT_MS = WORKTREE_OPERATION_TIMEOUT_MS;
export const WORKTREE_CREATE_TIMEOUT_MAX_MS = 1_800_000;
export const WORKTREE_PARTIAL_RECOVERY_TIMEOUT_MS = 10_000;
export const WORKTREE_PROCESS_CLOSE_CONFIRM_TIMEOUT_MS = 1_000;
export const WORKTREE_WINDOWS_TASKKILL_TIMEOUT_MS = 10_000;
