import { expect, it, vi } from 'vitest';
import { JevCardObservationPipeline } from '../src/cards/jev_card_observation_pipeline.js';
import { buildObservationInput } from '../src/cards/jev_card_observation.js';
import type { NodeRegistryEvent } from '../src/node/registry.js';
const event = (id: number, type = 'complete'): NodeRegistryEvent => ({ type: 'node_session_event', nodeId: 'node', data: { type: 'event', agentSessionId: 's', event: { type, _event_id: id } } });
it('duplicate complete calls once; debug never triggers; reload reservation prevents reevaluation', async () => {
  let reserved = false;
  const input = buildObservationInput({ completeEventId: 10, cards: [{ id: 'a', title: '작업', status: 'running', version: 1, request: '작업', brief: '', instruction: '', report: '' }], history: [], summaries: [], startObservations: [], totalCards: 1 });
  const evaluate = vi.fn(async () => ({ status: 'not_evaluated' as const, reason: 'error' as const, calls: 1, latencyMs: 4, inputBytes: 20, cards: [] }));
  const publish = vi.fn();
  const deps = { repository: { load: async (j: any) => ({ job: { ...j, finalResponseEventId: 9, previousCompleteEventId: 1, capturedAt: 'now' }, input }), claim: async () => { if (reserved) return false; reserved = true; return true; }, append: async (job: any) => ({ eventId: 20, payload: { final_response_event_id: job.finalResponseEventId } }) }, apiKey: 'key', evaluate, publish, log: vi.fn() };
  const pipeline = new JevCardObservationPipeline(deps);
  pipeline.accept([event(10), event(10), event(12, 'debug'), event(13, 'session_ended')]);
  await pipeline.drain();
  expect(evaluate).toHaveBeenCalledTimes(1);
  expect(publish.mock.calls[0][2]).toEqual({ final_response_event_id: 9 });
  const restarted = new JevCardObservationPipeline(deps);
  restarted.accept([event(10)]);
  await restarted.drain();
  expect(evaluate).toHaveBeenCalledTimes(1);
});
it('accept does not wait for provider and late responses retain their own turn anchors', async () => {
  const pending: Array<(value: any) => void> = [];
  const input = buildObservationInput({ completeEventId: 1, cards: [{ id: 'a', title: '작업', status: 'running', version: 1, request: '', brief: '', instruction: '', report: '' }], history: [], summaries: [], startObservations: [], totalCards: 1 });
  const publish = vi.fn();
  const pipeline = new JevCardObservationPipeline({ repository: { load: async (job: any) => ({ job: { ...job, finalResponseEventId: job.completeEventId - 1 }, input }), claim: async () => true, append: async (job: any) => ({ eventId: job.completeEventId + 100, payload: { final_response_event_id: job.finalResponseEventId } }) }, apiKey: 'key', evaluate: () => new Promise(resolve => pending.push(resolve)), publish, log: vi.fn() });
  expect(pipeline.accept([event(10), event(20)])).toBeUndefined();
  await new Promise(resolve => setTimeout(resolve, 0));
  pending[1]({ status: 'evaluated', cards: [], calls: 1 });
  await new Promise(resolve => setTimeout(resolve, 0));
  pending[0]({ status: 'evaluated', cards: [], calls: 1 });
  await pipeline.drain();
  expect(publish.mock.calls.map(args => args[2].final_response_event_id)).toEqual([19, 9]);
});
